### PR TITLE
kungfu-notify-start (#302)

### PR DESCRIPTION
**Pull request by lgarithm**

### CODE REVIEW

**Comment by lgarithm** [comment]
@zrss

**Comment by zrss** [comment]
get it

**Comment by zrss** [comment]
@lgarithm , unfortunately, it still not work ... i did gdb attach to the process, and try to find something useful for debug this weired bug

but the stack trace info lack of `libkungfu.so`, as

```
Thread 185 (Thread 0x7f5419fff700 (LWP 3407)):
#0  0x00007f55e4131edd in runtime.pcvalue (f=..., off=1758928, targetpc=140006877913432, cache=0x7f5419ffebc0,
    strict=true, ~r5=<optimized out>) at /usr/local/go/src/runtime/symtab.go:674
#1  0x00007f55e4132938 in runtime.pcdatavalue (f=..., table=1, targetpc=140006877913432, cache=0x7f5419ffebc0,
    ~r4=<optimized out>) at /usr/local/go/src/runtime/symtab.go:790
#2  0x00007f55e412eade in runtime.getStackMap (frame=0x7f5419ffeab0, cache=0x7f5419ffebc0, debug=<optimized out>,
    locals=..., args=..., objs=...) at /usr/local/go/src/runtime/stack.go:1187
#3  0x00007f55e41079d6 in runtime.scanframeworker (frame=0x7f5419ffeab0, state=0x7f5419ffebc0, gcw=0xc00002b770)
    at /usr/local/go/src/runtime/mgcmark.go:817
#4  0x00007f55e413dedf in runtime.scanstack.func1 (frame=0x7f5419ffeab0, unused=<optimized out>, ~r2=<optimized out>)
    at /usr/local/go/src/runtime/mgcmark.go:708
#5  0x00007f55e4136b81 in runtime.gentraceback (pc0=18446744073709551615, sp0=18446744073709551615, lr0=<optimized out>,
    gp=0xc000280300, skip=0, pcbuf=0x0, max=2147483647, callback=
    {void (runtime.stkframe *, void *, bool *)} 0x7f5419ffeb50, v=0x0, flags=0, ~r10=<optimized out>)
    at /usr/local/go/src/runtime/traceback.go:334
#6  0x00007f55e4107351 in runtime.scanstack (gp=0xc000280300, gcw=0xc00002b770)
    at /usr/local/go/src/runtime/mgcmark.go:711
#7  0x00007f55e4119735 in runtime.scang (gp=0xc000280300, gcw=0xc00002b770) at /usr/local/go/src/runtime/proc.go:886
#8  0x00007f55e413ddd1 in runtime.markroot.func1 () at /usr/local/go/src/runtime/mgcmark.go:221
#9  0x00007f55e41063d5 in runtime.markroot (gcw=0xc00002b770, i=67) at /usr/local/go/src/runtime/mgcmark.go:202
#10 0x00007f55e4107c74 in runtime.gcDrain (gcw=0xc00002b770, flags=3) at /usr/local/go/src/runtime/mgcmark.go:915
#11 0x00007f55e413dc32 in runtime.gcBgMarkWorker.func2 () at /usr/local/go/src/runtime/mgc.go:1904
#12 0x00007f55e4140df3 in runtime.systemstack () at /usr/local/go/src/runtime/asm_amd64.s:370
#13 0x00007f55e411a160 in ?? () at /usr/local/go/src/runtime/proc.go:1080
   from /home/work/anaconda/lib/python3.6/site-packages/kungfu/libkungfu.so
#14 0x0000000000000000 in ?? ()
```

**Comment by zrss** [comment]
we test the newest code, now it works, thanks @lgarithm

**Comment by luomai** [comment]
LGTM after adding the documents for this elastic mode.

**Pull request merged**
