### PR TITLE
support launch with python multiprocess

### PR DESCRIPTION
**Pull request by lgarithm**
e.g.

```
./examples/multiprocess/tf_multiprocess.py
./examples/multiprocess/torch_multiprocess.py
```

### CODE REVIEW

**Comment by lgarithm** [comment]
@ZenoTan

**Comment by ZenoTan** [comment]
- Could we add *args to `launch_multiprocess`?
- How do we construct optimizers? `import kungfu.torch as kf
            optimizer = kf.optimizers.SynchronousSGDOptimizer(
                optimizer, named_parameters=model.named_parameters())
            kf.broadcast_parameters(model.state_dict())`

**Comment by lgarithm** [comment]
For passing extra args, you can wrap the worker with a functor, e.g.

```python
#!/usr/bin/env python3

import torch
from kungfu.cmd import launch_multiprocess


def worker(rank):
    import kungfu.torch as kf
    from kungfu.python import current_cluster_size, current_rank
    print('rank=%d' % (rank))
    print('kungfu rank: %d, size %d' %
          (current_rank(), current_cluster_size()))
    x = torch.ones([]) * int(current_rank())
    print(x)
    y = kf.ops.collective.all_reduce_fn(x)
    print(y)


class Worker():
    def __init__(self, f, args):
        self._args = args
        self._f = f

    def __call__(self, rank):
        self._f(self._args[rank])


def main():
    np = 4
    args = list(range(np))
    launch_multiprocess(Worker(worker, args), np)


main()
```

**Comment by ZenoTan** [comment]
Great. What about the second question: kungfu optimizer can still be used as before, like what we have in quiver?

**Comment by lgarithm** [comment]
I think it should be the same.

They only thing that need to be careful is, don't include other kungfu module before `launch_multiprocess`, otherwise the main process will be initialized as a kungfu process.

**Review by luomai — APPROVED** [review]

**Pull request merged**
